import { Exercise } from '../../src/modules/training/entities/exercise.entity';
import { MuscleGroup } from '../../src/common/enums/muscle-group.enum';
import { TrainingIntensity } from '../../src/common/enums/training-intensity.enum';

export const EXERCISES = [
  {
    name: 'Push-ups',
    description: 'A classic bodyweight exercise for chest and triceps.',
    primaryMuscleGroup: MuscleGroup.CHEST,
    intensity: TrainingIntensity.MODERATE,
    metValue: 3.8,
  },
  {
    name: 'Squats',
    description: 'Fundamental lower body exercise for quads and glutes.',
    primaryMuscleGroup: MuscleGroup.LEGS,
    intensity: TrainingIntensity.MODERATE,
    metValue: 5.0,
  },
  {
    name: 'Running (Fast)',
    description: 'High-intensity cardiovascular workout.',
    primaryMuscleGroup: MuscleGroup.CARDIO,
    intensity: TrainingIntensity.HEAVY,
    metValue: 12.0,
  },
  {
    name: 'Walking (Casual)',
    description: 'Low-intensity recovery walk.',
    primaryMuscleGroup: MuscleGroup.CARDIO,
    intensity: TrainingIntensity.LIGHT,
    metValue: 3.0,
  },
  {
    name: 'Plank',
    description: 'Core stability exercise.',
    primaryMuscleGroup: MuscleGroup.CORE,
    intensity: TrainingIntensity.LIGHT,
    metValue: 2.8,
  },
  {
    name: 'Bicep Curls',
    description: 'Isolation exercise for the biceps.',
    primaryMuscleGroup: MuscleGroup.ARMS,
    intensity: TrainingIntensity.MODERATE,
    metValue: 3.0,
  },
  {
    name: 'Deadlifts',
    description: 'Compound lift for the back and posterior chain.',
    primaryMuscleGroup: MuscleGroup.BACK,
    intensity: TrainingIntensity.HEAVY,
    metValue: 6.0,
  },
  {
    name: 'Shoulder Press',
    description: 'Overhead press for the deltoids.',
    primaryMuscleGroup: MuscleGroup.SHOULDERS,
    intensity: TrainingIntensity.MODERATE,
    metValue: 4.0,
  },
  {
    name: 'Pull-ups',
    description: 'Upper body pulling exercise.',
    primaryMuscleGroup: MuscleGroup.BACK,
    intensity: TrainingIntensity.MODERATE,
    metValue: 5.0,
  },
  {
    name: 'Lunges',
    description: 'Lower body unilateral exercise.',
    primaryMuscleGroup: MuscleGroup.LEGS,
    intensity: TrainingIntensity.MODERATE,
    metValue: 4.1,
  },
  {
    name: 'Burpees',
    description: 'Full body explosive movement.',
    primaryMuscleGroup: MuscleGroup.FULL_BODY,
    intensity: TrainingIntensity.HEAVY,
    metValue: 8.0,
  },
  {
    name: 'Dips',
    description: 'Triceps focused bodyweight exercise.',
    primaryMuscleGroup: MuscleGroup.ARMS,
    intensity: TrainingIntensity.MODERATE,
    metValue: 3.5,
  },
  {
    name: 'Leg Press',
    description: 'Machine based leg exercise.',
    primaryMuscleGroup: MuscleGroup.LEGS,
    intensity: TrainingIntensity.MODERATE,
    metValue: 3.0,
  },
  {
    name: 'Crunches',
    description: 'Abdominal isolation.',
    primaryMuscleGroup: MuscleGroup.CORE,
    intensity: TrainingIntensity.LIGHT,
    metValue: 2.5,
  },
  {
    name: 'Bench Press',
    description: 'Chest compound movement.',
    primaryMuscleGroup: MuscleGroup.CHEST,
    intensity: TrainingIntensity.HEAVY,
    metValue: 5.0,
  },
  {
    name: 'Swimming (Moderate)',
    description: 'Caloric burning full body.',
    primaryMuscleGroup: MuscleGroup.CARDIO,
    intensity: TrainingIntensity.MODERATE,
    metValue: 7.0,
  },
  {
    name: 'Cycling (Fast)',
    description: 'High speed cycling.',
    primaryMuscleGroup: MuscleGroup.CARDIO,
    intensity: TrainingIntensity.HEAVY,
    metValue: 10.0,
  },
  {
    name: 'Mountain Climbers',
    description: 'Core and cardio.',
    primaryMuscleGroup: MuscleGroup.CORE,
    intensity: TrainingIntensity.MODERATE,
    metValue: 4.5,
  },
  {
    name: 'Russian Twists',
    description: 'Obliques focus.',
    primaryMuscleGroup: MuscleGroup.CORE,
    intensity: TrainingIntensity.LIGHT,
    metValue: 2.3,
  },
  {
    name: 'Tricep Extensions',
    description: 'Isolation triceps.',
    primaryMuscleGroup: MuscleGroup.ARMS,
    intensity: TrainingIntensity.MODERATE,
    metValue: 3.0,
  },
  {
    name: 'Hammer Curls',
    description: 'Isolation biceps/forearms.',
    primaryMuscleGroup: MuscleGroup.ARMS,
    intensity: TrainingIntensity.MODERATE,
    metValue: 2.8,
  },
  {
    name: 'Lateral Raises',
    description: 'Isolation shoulders.',
    primaryMuscleGroup: MuscleGroup.SHOULDERS,
    intensity: TrainingIntensity.LIGHT,
    metValue: 2.0,
  },
  {
    name: 'Bulgarian Split Squats',
    description: 'Intense unilateral legs.',
    primaryMuscleGroup: MuscleGroup.LEGS,
    intensity: TrainingIntensity.HEAVY,
    metValue: 6.0,
  },
  {
    name: 'Hip Thrusts',
    description: 'Glute isolation.',
    primaryMuscleGroup: MuscleGroup.LEGS,
    intensity: TrainingIntensity.MODERATE,
    metValue: 3.5,
  },
  {
    name: 'Calf Raises',
    description: 'Isolation calves.',
    primaryMuscleGroup: MuscleGroup.LEGS,
    intensity: TrainingIntensity.LIGHT,
    metValue: 1.5,
  },
  {
    name: 'Lat Pulldowns',
    description: 'Back focus.',
    primaryMuscleGroup: MuscleGroup.BACK,
    intensity: TrainingIntensity.MODERATE,
    metValue: 3.5,
  },
  {
    name: 'Face Pulls',
    description: 'Rear delts/traps.',
    primaryMuscleGroup: MuscleGroup.SHOULDERS,
    intensity: TrainingIntensity.LIGHT,
    metValue: 2.0,
  },
  {
    name: 'Leg Curls',
    description: 'Hamstring isolation.',
    primaryMuscleGroup: MuscleGroup.LEGS,
    intensity: TrainingIntensity.LIGHT,
    metValue: 2.0,
  },
  {
    name: 'Face Down Planks',
    description: 'Static core.',
    primaryMuscleGroup: MuscleGroup.CORE,
    intensity: TrainingIntensity.LIGHT,
    metValue: 2.5,
  },
  {
    name: 'Box Jumps',
    description: 'Plyometric explosive.',
    primaryMuscleGroup: MuscleGroup.LEGS,
    intensity: TrainingIntensity.HEAVY,
    metValue: 7.5,
  },
];
